// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZUOEpHUTWpYZcZLiCBsLtEjwEWDV_4Cg',
    appId: '1:460001596315:android:1f29c20013a3025b23473e',
    messagingSenderId: '460001596315',
    projectId: 'test-a9c1a',
    databaseURL: 'https://test-a9c1a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-a9c1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDBi8S_v3myGkn2nl-OTXDckXJgQ10GtA',
    appId: '1:460001596315:ios:51f700cf8cd87a2123473e',
    messagingSenderId: '460001596315',
    projectId: 'test-a9c1a',
    databaseURL: 'https://test-a9c1a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-a9c1a.appspot.com',
    iosClientId: '460001596315-ar5f018m1v2vfgsj3baqbutb6vfauvdl.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDBi8S_v3myGkn2nl-OTXDckXJgQ10GtA',
    appId: '1:460001596315:ios:b3d6915d2376c51a23473e',
    messagingSenderId: '460001596315',
    projectId: 'test-a9c1a',
    databaseURL: 'https://test-a9c1a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-a9c1a.appspot.com',
    iosClientId: '460001596315-abudrfqcabbjajc3ccaokrrfdlvtc5oo.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
